import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import '../models/channel_listing.dart';
import '../models/cue.dart';
import 'subtitle_parser.dart';

final RegExp _youtubeUrlPattern = RegExp(
  r'^https?:\/\/(youtu\.be\/|(www\.)?youtube\.com\/(embed|v|shorts)\/)',
  caseSensitive: false,
);

class YoutubeRepository {
  YoutubeRepository({YoutubeExplode? explode})
      : _explode = explode ?? YoutubeExplode();

  final YoutubeExplode _explode;

  void close() => _explode.close();

  bool isValidYoutubeUrl(String url) {
    final trimmed = url.trim();
    if (trimmed.isEmpty) return false;
    try {
      final uri = Uri.parse(trimmed);
      const hosts = {
        'youtube.com',
        'www.youtube.com',
        'm.youtube.com',
        'music.youtube.com',
        'gaming.youtube.com',
        'youtu.be',
      };
      if (hosts.contains(uri.host.toLowerCase())) return true;
      return _youtubeUrlPattern.hasMatch(trimmed);
    } catch (_) {
      return false;
    }
  }

  String? extractVideoId(String url) {
    try {
      return VideoId.parseVideoId(url.trim());
    } catch (_) {
      return null;
    }
  }

  Future<({String title, Duration? duration})> fetchVideoMeta(
    String videoId,
  ) async {
    final video = await _explode.videos.get(videoId);
    return (title: video.title, duration: video.duration);
  }

  Future<Uri> streamUrlForVideo(String videoId) async {
    final manifest = await _explode.videos.streamsClient.getManifest(videoId);
    final stream = manifest.muxed.withHighestBitrate();
    return stream.url;
  }

  Future<({List<Cue> raw, List<Cue> merged})> fetchEnglishCaptionTracks(
    String videoId,
  ) async {
    final manifest =
        await _explode.videos.closedCaptions.getManifest(videoId);

    final enTracks =
        manifest.getByLanguage('en', autoGenerated: true);
    final trackInfo = enTracks.isNotEmpty
        ? enTracks.first
        : manifest.tracks.firstWhere(
            (t) => t.language.code.toLowerCase().startsWith('en'),
            orElse: () => manifest.tracks.first,
          );

    final track = await _explode.videos.closedCaptions.get(trackInfo);
    final raw = cuesFromClosedCaptions(track.captions);
    return (raw: raw, merged: mergeCuesIntoSentences(raw));
  }

  Future<List<Cue>> fetchEnglishCaptions(String videoId) async {
    final tracks = await fetchEnglishCaptionTracks(videoId);
    return tracks.merged;
  }

  /// `@Friends`, `https://www.youtube.com/@Friends`, or channel id `UC...`.
  String? parseChannelInput(String input) {
    final trimmed = input.trim();
    if (trimmed.isEmpty) return null;
    if (trimmed.startsWith('@')) return trimmed;

    final uri = Uri.tryParse(trimmed);
    if (uri != null) {
      final segments = uri.pathSegments;
      for (var i = 0; i < segments.length; i++) {
        final seg = segments[i];
        if (seg.startsWith('@')) return seg;
        if (seg == 'channel' && i + 1 < segments.length) {
          return segments[i + 1];
        }
      }
    }

    if (!trimmed.contains('/') && !trimmed.contains('.')) {
      return trimmed.startsWith('UC') ? trimmed : '@$trimmed';
    }
    return null;
  }

  Future<ChannelListing> fetchChannelVideos(String input) async {
    final key = parseChannelInput(input);
    if (key == null) {
      throw ArgumentError('无法识别频道：$input');
    }

    final Channel channel;
    if (key.startsWith('@')) {
      channel = await _explode.channels.getByHandle(key);
    } else {
      channel = await _explode.channels.get(key);
    }

    final uploads = await _explode.channels.getUploadsFromPage(channel.id);
    final videos = await _enrichChannelVideoItems(uploads);

    return ChannelListing(channelTitle: channel.title, videos: videos);
  }

  /// Channel upload grid often omits title/duration (YouTube lockup layout).
  Future<List<ChannelVideoItem>> _enrichChannelVideoItems(
    Iterable<Video> uploads,
  ) async {
    const batchSize = 8;
    final list = uploads.toList();
    final items = <ChannelVideoItem>[];
    for (var i = 0; i < list.length; i += batchSize) {
      final end = i + batchSize < list.length ? i + batchSize : list.length;
      final batch = await Future.wait(
        list.sublist(i, end).map(_channelVideoItemFromUpload),
      );
      items.addAll(batch);
    }
    return items;
  }

  Future<ChannelVideoItem> _channelVideoItemFromUpload(Video v) async {
    var title = v.title;
    var duration = v.duration;
    if (title.isEmpty || (duration?.inSeconds ?? 0) <= 0) {
      final full = await _explode.videos.get(v.id);
      title = full.title;
      duration = full.duration;
    }
    return ChannelVideoItem(
      videoId: v.id.value,
      title: title,
      watchUrl: v.url,
      thumbnailUrl: v.thumbnails.mediumResUrl,
      duration: duration,
    );
  }
}
